# application.yaml

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homestay_db?useSSL=false&serverTimezone=UTC
    username: root
    password: your_mysql_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

cloudinary:
  cloud-name: your_cloud_name
  api-key: your_api_key
  api-secret: your_api_secret

jwt:
  secret: your_jwt_secret
  expirationMs: 86400000

vnpay:
  tmnCode: Q8CSPVFP
  hashSecret: XFYN1U5CGM1W4FK02TZP9WTYGJK4UTYU
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/payment/vnpay-return
