server:
  port: 8080
  servlet:
    context-path: /homestay

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/homestay"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "nL8Wk3q9TuXFeV+JkzAmYZcRpGfM2y8PvqLdWz3aHTG9eV7uKqV3lSn5eLZCq4US"
  expiration: 86400000

cloudinary:
  cloud_name: deyu8aoef
  api_key: 642675988451599
  api_secret: 4IXsKibWyB2isTTkCWQ0oP7_l5s

#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG
#    org.springframework.security: DEBUG
payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    returnUrl: "http://127.0.0.1:5500/homestay.html"
    tmnCode: "LQXA5GI7"
    secretKey: "A28G1KEYXT6M841R8H55SXR0QEMU8T0D"
    version: "2.1.0"
    command: "pay"
    orderType: "other"


