server:
  port: 8080
  servlet:
    context-path: /homestay

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/homestay"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "nL8Wk3q9TuXFeV+JkzAmYZcRpGfM2y8PvqLdWz3aHTG9eV7uKqV3lSn5eLZCq4US"
  expiration: 86400000

cloudinary:
  cloud_name: deyu8aoef
  api_key: 642675988451599
  api_secret: 4IXsKibWyB2isTTkCWQ0oP7_l5s

vnpay:
  tmnCode: Q8CSPVFP
  hashSecret: ZCI8YJYBU5DW2IYHHIA6XDMFJS5WJMB2
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/homestay/api/payment/vnpay-return
